### ISSUE TITLE
Not really an issue, just a question

### ISSUE THREAD

**Issue by tinokremer** [kylewm/KnownReactions#1]
I'm very excited about this, specially the Indieweb "Like". I grabbed this branch and tried to install it on my Known (selfhosted) installation. It throws errors at the vendor/autoload.php though:
`[Mon Feb 01 20:08:37.148583 2016] [proxy_fcgi:error] [pid 30788:tid 140317722277632] [client 84.84.196.80:54203] AH01071: Got error 'PHP message: PHP Warning:  require_once(/home/kremerti/domains/tinokremer.nl/public_html/IdnoPlugins/Reactions/vendor/autoload.php): failed to open stream: No such file or directory in /home/kremerti/domains/tinokremer.nl/public_html/IdnoPlugins/Reactions/Main.php on line 6\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/home/kremerti/domains/tinokremer.nl/public_html/IdnoPlugins/Reactions/vendor/autoload.php' (include_path='/home/kremerti/domains/tinokremer.nl/public_html/external/htmlpurifier-lite/library:.:/usr/local/php56/lib/php') in /home/kremerti/domains/tinokremer.nl/public_html/IdnoPlugins/Reactions/Main.php on line 6\n', referer: https://tinokremer.nl/admin/plugins/` 

I did try to comment that out and tried to get the references to work, but I'm not a PHP guy (yet).

Is it just not finished enough or is there a pointer you could give me? I'm running my Known installation on a webhost. I do have access to the control panel, but my access to the server configuration is limited.

**Comment by kylewm** [comment]
Hi @tinokremer, Thanks for trying it out and sorry for the bad/no documentation! I'll fix that.

The plugin uses Composer to pull in library dependencies. As such you have to [install composer](https://getcomposer.org/) and then run `composer install` in the plugin's directory.

I think it is also possible for me to upload dist packages through Github that will bundle everything you need into a zip and won't require composer. I need to make one change to the template stuff so that it doesn't conflict with the Bookmark plugin's templates, and then I will see about doing that.

**Comment by tinokremer** [comment]
That's great @kylewm. I do not have access to the shell on my shared hosting account, which I think is required to install and/or use composer. I'm patient, there is no rush. If you would be so kind to provide a package at some point that would be totally awesome! :)

**Comment by kylewm** [comment]
I posted a zip here https://github.com/kylewm/KnownReactions/releases/tag/0.1.0 but unfortunately it still conflicts with the bookmarks plugin (they both lay claim to the /like/edit route, so you only get one editor or the other, whichever one is loaded first), and the icons won't work quite right yet (submitted a PR to core for that).

I'll try to sort out the conflicting issue in the near future.

I'm working on updates to the Twitter plugin this morning so that likes/retweets will actually posse to Twitter too.

Thanks again for your interest :)

**Comment by tinokremer** [comment]
Nice, thanks @kylewm, I got it to work now. I do not think the webmentions are sent (correctly) yet, but both a LIKE and REPOST are stored on my site now. I'll dig into it in a bit. Thanks again!

**Comment by kylewm** [comment]
heh, you're right: I was also just noticing that webmentions aren't being sent.
