### ISSUE TITLE
Repost should get ride of some WP stuff before publish

### ISSUE THREAD

**Issue by rikmendes** [kylewm/KnownReactions#11]
What I did : 

Take this URL http://boffosocko.com/2016/06/06/webmention-books-bookmention/ and repost it on your Known site. 

What happened : 

the post get fetched but includes links to share to facebook, and syndicated links to the silo copies of the original post. 
![screenshot_224](https://cloud.githubusercontent.com/assets/12155003/15827625/26ce4da2-2c0c-11e6-84ff-5289187d9d49.png)
![screenshot_223](https://cloud.githubusercontent.com/assets/12155003/15827618/2229c09c-2c0c-11e6-89d8-ebc6ff7a98bd.png)

What should happen : 

can we skip anything related to templates, authors, share plugins ?
![screenshot_225](https://cloud.githubusercontent.com/assets/12155003/15827655/4c95b16a-2c0c-11e6-848e-355d267e8d37.png)

**Comment by rikmendes** [comment]
testing repost from petermolnar.eu (WP indieweb site)  work just fine, without WP stuff coming in, just the text Post
so maybe this has nothing to do with this plugin and more with the source site itself ?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/kylewm/KnownReactions/issues/11" class="u-in-reply-to"></a>I'd mentioned something like this a while back at https://github.com/dshanske/syndication-links/issues/23 as I was seeing it in pop up in Woodwind.xyz and a few other places.  I'm not quite sure what's causing the problem (which is sporadic and depends on who's resharing or where it's being resyndicated to.)  In general it's not a problem with KnownReactions (really), but something to do with the WordPress install/configuration.  

I'm hoping that @dshanske and the fix he mentioned clears it up, but if not I'll continue to look into it on the WP side, because I want to get rid of it too. This is the first time I've seen the "related", "author", and "share" this portions show up. Usually it's just the blank "Syndicated to" portions that sneak in. (I've also seen this with POSSE from WP to Tumblr as well as with Woodwind. I haven't seen it happen on many other platforms however.)

**Comment by kylewm** [comment]
Thanks @chrisaldrich, yep this is a problem with the microformats classes on the target page (`e-content` contains too much stuff .. it should just be the post content, not all the footer information too).
