### ISSUE TITLE
Likes not showing url

### ISSUE THREAD

**Issue by danito** [kylewm/KnownReactions#17]
Hi,
I didn't pay attention before, but if I like a site, it's url doesn't show up nowhere.
Is this a bug or a feature?
(see http://nxd4n.nixekinder.be/2016/liked-felix-schwenzels-emotionalit%C3%A4t-leichtigkeit-unabh%C3%A4ngigkeit-e02eb65e09)

**Comment by rikmendes** [comment]
Got the same with a tweet I liked the other day... Wasn't sure it was a bug or not.
But I'm not even sure the reactions plug-in is to like URL's out of twitter.. See what I mean? 
Le 26 oct. 2016 6:15 PM, Daniel nix <notifications@github.com> a écrit :Hi,
I didn't pay attention before, but if I like a site, it's url doesn't show up nowhere.
Is this a bug or a feature?
(see http://nxd4n.nixekinder.be/2016/liked-felix-schwenzels-emotionalit%C3%A4t-leichtigkeit-unabh%C3%A4ngigkeit-e02eb65e09)

**Comment by chrisaldrich** [comment]
<a href="http://stream.boffosocko.com/2016/liked-daniel-nixs-daniel-nix-felix-schwenzels-emotionalit%C3%A4t-leichtigkeit-unabh%C3%A4ngigkeit" class="u-in-reply-to"></a><a href="https://nxd4n.nixekinder.be/2016/seems-you-fixed-the-like-plugin-in-a-way-likeception-let-us-know-how-1" class="u-in-reply-to"></a><a href="https://github.com/kylewm/KnownReactions/issues/17" class="u-in-reply-to"></a>I tried the same post and didn't run into the same issue: 
http://stream.boffosocko.com/2016/liked-felix-schwenzels-emotionalit%C3%A4t-leichtigkeit-unabh%C3%A4ngigkeit-6d8e31d6d5

Though I also tried liking your original post @danito and got this:
http://stream.boffosocko.com/2016/liked-daniel-nixs-daniel-nix-felix-schwenzels-emotionalit%C3%A4t-leichtigkeit-unabh%C3%A4ngigkeit
The post includes the extraneous metadata "Daniel Nixpublished this 26 Oct 2016 0 stars 0 comments" in the title, rather than just the original title.  Perhaps you've got some code misplaced that's causing both issues for you?

I've run into the original problem a few times in the past, but it's typically been the target site having issues with http/https or security settings that don't allow the plugin to scrape the page properly. It's been relatively rare and I haven't run across it in a while. 

If I recall, the locations module had a (similar?) issue a while back that didn't fail gracefully when the system didn't return a location properly and it just hung. It was changed to allow it to fail and let the user enter/cut&paste the data manually. Depending on the root cause of the problem, perhaps this could be a solution? Is it even showing you the URL field before you approve the post? Could you enter it manually?

@rikmendes I'm not sure what you mean about Twitter URLs, though If I use it to "like" a tweet, I get something like this: http://stream.boffosocko.com/2016/liked-weaverbots-tweet-e29c8c3952 and Known sends the "like" intent to Twitter and revisiting the tweet shows my "heart" properly as I'd expect it.  From a UI perspective, it would be nice if Known and KnownReactions would actually save a blockquoted version of the tweet so I was saving the data of the post I was liking (particularly for short content like tweets), though saving the data for longer blog posts/articles, this isn't necessarily the best thing and a link to the original is fine.

**Comment by danito** [comment]
It's strange. When you like a post, you get the right template to show Like.tpl.php:
````html
<div class="e-content entry-content">
                        <i class="fa fa-star-o"></i>
Liked
<a class="u-like-of" href="https://wirres.net/article/articleview/10307/1/6">
````

I get 
````html
<div class="known-bookmark">
                <h2 class="p-bookmark">
             <i class="fa fa-star-o"></i> <a href="" rel="bookmark" target="_blank"></a>
            </h2>
        
<p>felix schwenzel's emotionalität, leichtigkeit, unabhängigkeit</p>
</div>
````
Seems that it's not applying the right template.
I probably fixed something else which broke this...

**Comment by danito** [comment]
The latest version let the user enter a description if there's a problem fetching it, so, no, this isn't the problem as I get the description from all the sites. Fetch.php works fine.
I'm just wondering if the original Like(Bookmark) plugin is not in my way and takes the lead (and that's why I get the known-bookmark class.

**Comment by kylewm** [comment]
> I'm just wondering if the original Like(Bookmark) plugin is not in my way and takes the lead (and that's why I get the known-bookmark class.

I think you're definitely onto something. `known-bookmark` tries to handle likes as well. There's a hack here: https://github.com/kylewm/KnownReactions/blob/master/Main.php#L16 that tries to move KnownReactions ahead of Bookmarks in the list of plugins.  Maybe the bookmark content type (`\IdnoPlugins\Like\ContentType`) changed to something else and this hack isn't working anymore?

**Comment by TechLifeWeb** [comment]
Came here to look into this.  Still not working. And reposts/retweets are worse. They show nothing at all. (example http://stream.techlifeweb.com/2017/repost-of-launch-tickers-tweet-2c6d8579d4). My Known instance is brand new so either I broke something or the core Known code changed.

**Comment by TechLifeWeb** [comment]
I've narrowed this down a little bit and it has some things to do with the order you enable plugins. My current order: Status, Bookmarks, Text Posts, Photos, Audio, Reactions. Doing that, Likes come up with a star with no link or embed. Reposts show nothing as indicated above.

**Comment by dg01d** [comment]
Without Bookmarks enabled, a Like/Repost shows nothing at all.

With Bookmarks enabled there is no 'u-like-of' present, instead there is 'p-bookmark'

**Comment by mruncieman** [comment]
I've recently upgraded my instance of Known and have run into this exact same issue. I've tried a few different approaches to try to get it working again, but no luck so far.

**Comment by rikmendes** [comment]
problem is ongoing on my Known instance, wondering what I can do to further debug this and find a solution for all..

**Comment by rikmendes** [comment]
it's not just likes that are not showing up, reshare are also sent to my Known but no way to click on the link from my instance..
not sure what I can do to provide more details, but willing to test debug if needed..
![screen shot 2017-08-04 at 14 49 04](https://user-images.githubusercontent.com/12155003/28973158-b472038c-7932-11e7-9cae-9d0078459ed7.png)

**Comment by funwhilelost** [comment]
@rikmendes @mruncieman - I've just submitted a PR for the issue you're experiencing.  It doesn't solve the Bookmarks conflict but it does make the Like and Repost appear in your feed.

If you don't mind monkey-patching your own installation then you can just move two files:
```
renamed:    templates/default/entity/IdnoPlugins/Reactions/Like.tpl.php -> templates/default/entity/Like.tpl.php
        renamed:    templates/default/entity/IdnoPlugins/Reactions/Repost.tpl.php -> templates/default/entity/Repost.tpl.php
```

**Comment by chrisaldrich** [comment]
Related: [Untangling @WithKnown plugin conflicts on the #IndieWeb (Reactions vs Bookmarks)](https://pvagner.tk/2018/untangling-withknown-plugin-conflicts-on-the-indieweb-reactions-vs-bookmarks)
